[workspace]
resolver = "2"
members = [
    "libxc", "libxc-ffi",
]

[workspace.package]
edition = "2021"
rust-version = "1.82"
version = "0.1.1"
description = "libxc FFI bindings and wrappers"
repository = "https://github.com/RESTGroup/libxc-rs"
keywords = ["ffi", "chemistry"]
categories = ["science"]
license = "Apache-2.0"

[workspace.dependencies]
libxc-ffi = { path = "libxc-ffi", version = "0.1.1" }
