//! Library struct definition for dynamic loading.
//!
//! This file is generated automatically.
//!
//! Note: For dynamic loading, API version features are ignored.
//! All functions are available at runtime. Runtime panic occurs if a function
//! is not found in the loaded library.

use super::*;
use core::ffi::{c_char, c_int};

pub struct DyLoadLib {
    pub __libraries: Vec<libloading::Library>,
    pub __libraries_path: Vec<String>,
    pub __error: Option<String>,
    pub xc_reference: Option<unsafe extern "C" fn() -> *const c_char>,
    pub xc_reference_doi: Option<unsafe extern "C" fn() -> *const c_char>,
    pub xc_reference_key: Option<unsafe extern "C" fn() -> *const c_char>,
    pub xc_version:
        Option<unsafe extern "C" fn(major: *mut c_int, minor: *mut c_int, micro: *mut c_int)>,
    pub xc_version_string: Option<unsafe extern "C" fn() -> *const c_char>,
    pub xc_func_reference_get_ref:
        Option<unsafe extern "C" fn(reference: *const func_reference_type) -> *const c_char>,
    pub xc_func_reference_get_doi:
        Option<unsafe extern "C" fn(reference: *const func_reference_type) -> *const c_char>,
    pub xc_func_reference_get_bibtex:
        Option<unsafe extern "C" fn(reference: *const func_reference_type) -> *const c_char>,
    pub xc_func_reference_get_key:
        Option<unsafe extern "C" fn(reference: *const func_reference_type) -> *const c_char>,
    pub xc_func_info_get_default_flags: Option<unsafe extern "C" fn() -> c_int>,
    pub xc_func_info_set_default_flags: Option<unsafe extern "C" fn(flags: c_int)>,
    pub xc_func_info_get_number:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> c_int>,
    pub xc_func_info_get_kind:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> c_int>,
    pub xc_func_info_get_name:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> *const c_char>,
    pub xc_func_info_get_family:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> c_int>,
    pub xc_func_info_get_flags:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> c_int>,
    pub xc_func_info_get_references: Option<
        unsafe extern "C" fn(
            info: *const xc_func_info_type,
            number: c_int,
        ) -> *const func_reference_type,
    >,
    pub xc_func_info_get_n_ext_params:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type) -> c_int>,
    pub xc_func_info_get_ext_params_name:
        Option<unsafe extern "C" fn(p: *const xc_func_info_type, number: c_int) -> *const c_char>,
    pub xc_func_info_get_ext_params_description: Option<
        unsafe extern "C" fn(info: *const xc_func_info_type, number: c_int) -> *const c_char,
    >,
    pub xc_func_info_get_ext_params_default_value:
        Option<unsafe extern "C" fn(info: *const xc_func_info_type, number: c_int) -> f64>,
    pub xc_functional_get_number: Option<unsafe extern "C" fn(name: *const c_char) -> c_int>,
    pub xc_functional_get_name: Option<unsafe extern "C" fn(number: c_int) -> *mut c_char>,
    pub xc_family_from_id:
        Option<unsafe extern "C" fn(id: c_int, family: *mut c_int, number: *mut c_int) -> c_int>,
    pub xc_number_of_functionals: Option<unsafe extern "C" fn() -> c_int>,
    pub xc_maximum_name_length: Option<unsafe extern "C" fn() -> c_int>,
    pub xc_available_functional_numbers: Option<unsafe extern "C" fn(list: *mut c_int)>,
    pub xc_available_functional_numbers_by_name: Option<unsafe extern "C" fn(list: *mut c_int)>,
    pub xc_available_functional_names: Option<unsafe extern "C" fn(list: *mut *mut c_char)>,
    pub xc_func_alloc: Option<unsafe extern "C" fn() -> *mut xc_func_type>,
    pub xc_func_init: Option<
        unsafe extern "C" fn(p: *mut xc_func_type, functional: c_int, nspin: c_int) -> c_int,
    >,
    pub xc_func_init_flags: Option<
        unsafe extern "C" fn(
            p: *mut xc_func_type,
            functional: c_int,
            nspin: c_int,
            flags: c_int,
        ) -> c_int,
    >,
    pub xc_func_end: Option<unsafe extern "C" fn(p: *mut xc_func_type)>,
    pub xc_func_free: Option<unsafe extern "C" fn(p: *mut xc_func_type)>,
    pub xc_func_get_info:
        Option<unsafe extern "C" fn(p: *const xc_func_type) -> *const xc_func_info_type>,
    pub xc_func_set_dens_threshold: Option<unsafe extern "C" fn(p: *mut xc_func_type, t_dens: f64)>,
    pub xc_func_set_zeta_threshold: Option<unsafe extern "C" fn(p: *mut xc_func_type, t_zeta: f64)>,
    pub xc_func_set_sigma_threshold:
        Option<unsafe extern "C" fn(p: *mut xc_func_type, t_sigma: f64)>,
    pub xc_func_set_tau_threshold: Option<unsafe extern "C" fn(p: *mut xc_func_type, t_tau: f64)>,
    pub xc_func_set_fhc_enforcement: Option<unsafe extern "C" fn(p: *mut xc_func_type, on: c_int)>,
    pub xc_func_set_ext_params:
        Option<unsafe extern "C" fn(p: *mut xc_func_type, ext_params: *const f64)>,
    pub xc_func_get_ext_params:
        Option<unsafe extern "C" fn(p: *const xc_func_type, ext_params: *mut f64)>,
    pub xc_func_set_ext_params_name:
        Option<unsafe extern "C" fn(p: *mut xc_func_type, name: *const c_char, par: f64)>,
    pub xc_func_get_ext_params_name:
        Option<unsafe extern "C" fn(p: *const xc_func_type, name: *const c_char) -> f64>,
    pub xc_func_get_ext_params_value:
        Option<unsafe extern "C" fn(p: *const xc_func_type, number: c_int) -> f64>,
    pub xc_lda_new: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            order: c_int,
            np: usize,
            rho: *const f64,
            out: *mut xc_lda_out_params,
        ),
    >,
    pub xc_gga_new: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            order: c_int,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            out: *mut xc_gga_out_params,
        ),
    >,
    pub xc_mgga_new: Option<
        unsafe extern "C" fn(
            func: *const xc_func_type,
            order: c_int,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            out: *mut xc_mgga_out_params,
        ),
    >,
    pub xc_lda: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            v2rho2: *mut f64,
            v3rho3: *mut f64,
            v4rho4: *mut f64,
        ),
    >,
    pub xc_gga: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rhosigma2: *mut f64,
            v3sigma3: *mut f64,
            v4rho4: *mut f64,
            v4rho3sigma: *mut f64,
            v4rho2sigma2: *mut f64,
            v4rhosigma3: *mut f64,
            v4sigma4: *mut f64,
        ),
    >,
    pub xc_mgga: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl_rho: *const f64,
            tau: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rho2lapl: *mut f64,
            v3rho2tau: *mut f64,
            v3rhosigma2: *mut f64,
            v3rhosigmalapl: *mut f64,
            v3rhosigmatau: *mut f64,
            v3rholapl2: *mut f64,
            v3rholapltau: *mut f64,
            v3rhotau2: *mut f64,
            v3sigma3: *mut f64,
            v3sigma2lapl: *mut f64,
            v3sigma2tau: *mut f64,
            v3sigmalapl2: *mut f64,
            v3sigmalapltau: *mut f64,
            v3sigmatau2: *mut f64,
            v3lapl3: *mut f64,
            v3lapl2tau: *mut f64,
            v3lapltau2: *mut f64,
            v3tau3: *mut f64,
            v4rho4: *mut f64,
            v4rho3sigma: *mut f64,
            v4rho3lapl: *mut f64,
            v4rho3tau: *mut f64,
            v4rho2sigma2: *mut f64,
            v4rho2sigmalapl: *mut f64,
            v4rho2sigmatau: *mut f64,
            v4rho2lapl2: *mut f64,
            v4rho2lapltau: *mut f64,
            v4rho2tau2: *mut f64,
            v4rhosigma3: *mut f64,
            v4rhosigma2lapl: *mut f64,
            v4rhosigma2tau: *mut f64,
            v4rhosigmalapl2: *mut f64,
            v4rhosigmalapltau: *mut f64,
            v4rhosigmatau2: *mut f64,
            v4rholapl3: *mut f64,
            v4rholapl2tau: *mut f64,
            v4rholapltau2: *mut f64,
            v4rhotau3: *mut f64,
            v4sigma4: *mut f64,
            v4sigma3lapl: *mut f64,
            v4sigma3tau: *mut f64,
            v4sigma2lapl2: *mut f64,
            v4sigma2lapltau: *mut f64,
            v4sigma2tau2: *mut f64,
            v4sigmalapl3: *mut f64,
            v4sigmalapl2tau: *mut f64,
            v4sigmalapltau2: *mut f64,
            v4sigmatau3: *mut f64,
            v4lapl4: *mut f64,
            v4lapl3tau: *mut f64,
            v4lapl2tau2: *mut f64,
            v4lapltau3: *mut f64,
            v4tau4: *mut f64,
        ),
    >,
    pub xc_lda_exc: Option<
        unsafe extern "C" fn(p: *const xc_func_type, np: usize, rho: *const f64, zk: *mut f64),
    >,
    pub xc_gga_exc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            zk: *mut f64,
        ),
    >,
    pub xc_mgga_exc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            zk: *mut f64,
        ),
    >,
    pub xc_lda_exc_vxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
        ),
    >,
    pub xc_gga_exc_vxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
        ),
    >,
    pub xc_mgga_exc_vxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
        ),
    >,
    pub xc_lda_vxc: Option<
        unsafe extern "C" fn(p: *const xc_func_type, np: usize, rho: *const f64, vrho: *mut f64),
    >,
    pub xc_gga_vxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
        ),
    >,
    pub xc_mgga_vxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
        ),
    >,
    pub xc_lda_exc_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            v2rho2: *mut f64,
        ),
    >,
    pub xc_gga_exc_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
        ),
    >,
    pub xc_mgga_exc_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
        ),
    >,
    pub xc_lda_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            vrho: *mut f64,
            v2rho2: *mut f64,
        ),
    >,
    pub xc_gga_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
        ),
    >,
    pub xc_mgga_vxc_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
        ),
    >,
    pub xc_lda_fxc: Option<
        unsafe extern "C" fn(p: *const xc_func_type, np: usize, rho: *const f64, v2rho2: *mut f64),
    >,
    pub xc_gga_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
        ),
    >,
    pub xc_mgga_fxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
        ),
    >,
    pub xc_lda_exc_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            v2rho2: *mut f64,
            v3rho3: *mut f64,
        ),
    >,
    pub xc_gga_exc_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rhosigma2: *mut f64,
            v3sigma3: *mut f64,
        ),
    >,
    pub xc_mgga_exc_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            zk: *mut f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rho2lapl: *mut f64,
            v3rho2tau: *mut f64,
            v3rhosigma2: *mut f64,
            v3rhosigmalapl: *mut f64,
            v3rhosigmatau: *mut f64,
            v3rholapl2: *mut f64,
            v3rholapltau: *mut f64,
            v3rhotau2: *mut f64,
            v3sigma3: *mut f64,
            v3sigma2lapl: *mut f64,
            v3sigma2tau: *mut f64,
            v3sigmalapl2: *mut f64,
            v3sigmalapltau: *mut f64,
            v3sigmatau2: *mut f64,
            v3lapl3: *mut f64,
            v3lapl2tau: *mut f64,
            v3lapltau2: *mut f64,
            v3tau3: *mut f64,
        ),
    >,
    pub xc_lda_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            vrho: *mut f64,
            v2rho2: *mut f64,
            v3rho3: *mut f64,
        ),
    >,
    pub xc_gga_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2sigma2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rhosigma2: *mut f64,
            v3sigma3: *mut f64,
        ),
    >,
    pub xc_mgga_vxc_fxc_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            vrho: *mut f64,
            vsigma: *mut f64,
            vlapl: *mut f64,
            vtau: *mut f64,
            v2rho2: *mut f64,
            v2rhosigma: *mut f64,
            v2rholapl: *mut f64,
            v2rhotau: *mut f64,
            v2sigma2: *mut f64,
            v2sigmalapl: *mut f64,
            v2sigmatau: *mut f64,
            v2lapl2: *mut f64,
            v2lapltau: *mut f64,
            v2tau2: *mut f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rho2lapl: *mut f64,
            v3rho2tau: *mut f64,
            v3rhosigma2: *mut f64,
            v3rhosigmalapl: *mut f64,
            v3rhosigmatau: *mut f64,
            v3rholapl2: *mut f64,
            v3rholapltau: *mut f64,
            v3rhotau2: *mut f64,
            v3sigma3: *mut f64,
            v3sigma2lapl: *mut f64,
            v3sigma2tau: *mut f64,
            v3sigmalapl2: *mut f64,
            v3sigmalapltau: *mut f64,
            v3sigmatau2: *mut f64,
            v3lapl3: *mut f64,
            v3lapl2tau: *mut f64,
            v3lapltau2: *mut f64,
            v3tau3: *mut f64,
        ),
    >,
    pub xc_lda_kxc: Option<
        unsafe extern "C" fn(p: *const xc_func_type, np: usize, rho: *const f64, v3rho3: *mut f64),
    >,
    pub xc_gga_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rhosigma2: *mut f64,
            v3sigma3: *mut f64,
        ),
    >,
    pub xc_mgga_kxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            v3rho3: *mut f64,
            v3rho2sigma: *mut f64,
            v3rho2lapl: *mut f64,
            v3rho2tau: *mut f64,
            v3rhosigma2: *mut f64,
            v3rhosigmalapl: *mut f64,
            v3rhosigmatau: *mut f64,
            v3rholapl2: *mut f64,
            v3rholapltau: *mut f64,
            v3rhotau2: *mut f64,
            v3sigma3: *mut f64,
            v3sigma2lapl: *mut f64,
            v3sigma2tau: *mut f64,
            v3sigmalapl2: *mut f64,
            v3sigmalapltau: *mut f64,
            v3sigmatau2: *mut f64,
            v3lapl3: *mut f64,
            v3lapl2tau: *mut f64,
            v3lapltau2: *mut f64,
            v3tau3: *mut f64,
        ),
    >,
    pub xc_lda_lxc: Option<
        unsafe extern "C" fn(p: *const xc_func_type, np: usize, rho: *const f64, v4rho4: *mut f64),
    >,
    pub xc_gga_lxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            v4rho4: *mut f64,
            v4rho3sigma: *mut f64,
            v4rho2sigma2: *mut f64,
            v4rhosigma3: *mut f64,
            v4sigma4: *mut f64,
        ),
    >,
    pub xc_mgga_lxc: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            np: usize,
            rho: *const f64,
            sigma: *const f64,
            lapl: *const f64,
            tau: *const f64,
            v4rho4: *mut f64,
            v4rho3sigma: *mut f64,
            v4rho3lapl: *mut f64,
            v4rho3tau: *mut f64,
            v4rho2sigma2: *mut f64,
            v4rho2sigmalapl: *mut f64,
            v4rho2sigmatau: *mut f64,
            v4rho2lapl2: *mut f64,
            v4rho2lapltau: *mut f64,
            v4rho2tau2: *mut f64,
            v4rhosigma3: *mut f64,
            v4rhosigma2lapl: *mut f64,
            v4rhosigma2tau: *mut f64,
            v4rhosigmalapl2: *mut f64,
            v4rhosigmalapltau: *mut f64,
            v4rhosigmatau2: *mut f64,
            v4rholapl3: *mut f64,
            v4rholapl2tau: *mut f64,
            v4rholapltau2: *mut f64,
            v4rhotau3: *mut f64,
            v4sigma4: *mut f64,
            v4sigma3lapl: *mut f64,
            v4sigma3tau: *mut f64,
            v4sigma2lapl2: *mut f64,
            v4sigma2lapltau: *mut f64,
            v4sigma2tau2: *mut f64,
            v4sigmalapl3: *mut f64,
            v4sigmalapl2tau: *mut f64,
            v4sigmalapltau2: *mut f64,
            v4sigmatau3: *mut f64,
            v4lapl4: *mut f64,
            v4lapl3tau: *mut f64,
            v4lapl2tau2: *mut f64,
            v4lapltau3: *mut f64,
            v4tau4: *mut f64,
        ),
    >,
    pub xc_gga_ak13_get_asymptotic: Option<unsafe extern "C" fn(homo: f64) -> f64>,
    pub xc_gga_ak13_pars_get_asymptotic:
        Option<unsafe extern "C" fn(homo: f64, ext_params: *const f64) -> f64>,
    pub xc_hyb_exx_coef: Option<unsafe extern "C" fn(p: *const xc_func_type) -> f64>,
    pub xc_hyb_cam_coef: Option<
        unsafe extern "C" fn(
            p: *const xc_func_type,
            omega: *mut f64,
            alpha: *mut f64,
            beta: *mut f64,
        ),
    >,
    pub xc_nlc_coef:
        Option<unsafe extern "C" fn(p: *const xc_func_type, nlc_b: *mut f64, nlc_C: *mut f64)>,
    pub xc_num_aux_funcs: Option<unsafe extern "C" fn(p: *const xc_func_type) -> c_int>,
    pub xc_aux_func_ids: Option<unsafe extern "C" fn(p: *const xc_func_type, ids: *mut c_int)>,
    pub xc_aux_func_weights:
        Option<unsafe extern "C" fn(p: *const xc_func_type, weights: *mut f64)>,
}
