[package]
name = "libxc-ffi"
description = "libxc C binding FFI"
readme = "readme.md"

rust-version.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
libloading = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["api-v7_0", "dynamic_loading"]

# Dynamic library loading support
dynamic_loading = ["dep:libloading"]

# API versions of original libxc (cumulative)
api-v6_2 = []
api-v7_0 = ["api-v6_2"]
api-v7_1 = ["api-v7_0"]
