name: test-v7.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-dynload-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests
        run: |
          conda install libxc python=3.11 -c conda-forge
          ls /usr/share/miniconda/lib
          cargo test -p libxc --no-default-features --features="api-v7_0" -- --nocapture
  
  test-dynload-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
      - name: run tests
        run: |
          conda install libxc=*=cuda* python=3.11 -c conda-forge
          ls /usr/share/miniconda/lib
          cargo test -p libxc --no-default-features --features="api-v7_0 cuda" -- --nocapture
